from seleniumbase import BaseCase
from faker import Faker

fake = Faker()

class TestPosts(BaseCase):
  def test_create_and_list(self):
    self.open('http://127.0.0.1:5000/auth/register')
    username = fake.name()
    self.type('input[name="username"]', username)
    self.type('input[name="password"]', "12345678")
    self.click('input[value="Register"]')
    self.open('http://127.0.0.1:5000')
    self.click_link("New")
    title = fake.sentence()
    body = fake.sentence()
    self.type('input[name="title"]', title)
    self.type('textarea[name="body"]', body)
    self.click('input[value="Save"]')
    self.assert_text(title)
    self.assert_text(body)

  def test_like_a_post(self):
    self.open('http://127.0.0.1:5000/auth/register')
    username = fake.name()
    self.type('input[name="username"]', username)
    self.type('input[name="password"]', "12345678")
    self.click('input[value="Register"]')
    self.click_link("Acebook")
    self.click_link("New")
    title = fake.sentence()
    body = fake.sentence()
    self.type('input[name="title"]', title)
    self.type('textarea[name="body"]', body)
    self.click('input[value="Save"]')
    self.click('input[value="Like"]')
    self.assert_text("You have liked this post!")
      
  def test_like_multiple_users(self):
    self.open('http://127.0.0.1:5000/auth/register')
    username = fake.name()
    self.type('input[name="username"]', username)
    self.type('input[name="password"]', "12345678")
    self.click('input[value="Register"]')
    self.click_link("Acebook")
    self.click_link("New")
    title = fake.sentence()
    body = fake.sentence()
    self.type('input[name="title"]', title)
    self.type('textarea[name="body"]', body)
    self.click('input[value="Save"]')
    self.click('input[value="Like"]')
    self.click_link("Log Out")
    self.click_link("Register")
    username2 = fake.name()
    self.type('input[name="username"]', username2)
    self.type('input[name="password"]', "12345678")
    self.click('input[value="Register"]')
    self.click_link("Acebook")
    self.click('input[value="Like"]')
    self.assert_text(f"Liked by:\n{username}\n{username2}")

  def test_like_not_working_if_not_logged_in(self):
    self.open('http://127.0.0.1:5000')
    self.click('input[value="Like"]')
    self.assert_text("Log In")

  def test_static_image_showing(self):
    self.open('http://127.0.0.1:5000/auth/register')
    username = fake.name()
    self.type('input[name="username"]', username)
    self.type('input[name="password"]', "12345678")
    self.click('input[value="Register"]')
    self.open('http://127.0.0.1:5000')
    self.click_link("New")
    title = fake.sentence()
    body = fake.sentence()
    self.type('input[name="title"]', title)
    self.type('textarea[name="body"]', body)
    self.click('input[value="Save"]')
    self.assert_element(f'img[src="{post.image}"]')